site_name: Helical AI Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
nav:
  - Home: index.md
  - Overview: 00-overview/README.md
  - Math:
      - Triangle Kernel: 10-math/math-spec.md
  - Architecture:
      - Helical Cell: 20-architecture/arch-spec.md
  - Experiments:
      - Index: 40-experiments/index.md
      - Baseline (2025-08-24): 40-experiments/experiment-2025-08-24-baseline.md
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
