site_name: Helical AI Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
nav:
  - Home: index.md
  - Overview: 00-overview/README.md
  - Math:
      - Triangle Kernel: 10-math/math-spec.md
  - Architecture:
      - Helical Cell: 20-architecture/arch-spec.md
